language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.10.5
branches:
  only:
    - master
bundler_args: --without production --path=vendor/bundle
cache:
  directories:
    - vendor/bundle
