language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.10.5
branches:
  only:
  - master
  - /^v[0-9]/
bundler_args: "--without production --path=vendor/bundle"
cache:
  directories:
  - vendor/bundle
deploy:
  provider: rubygems
  api_key:
    secure: VDNJFVROSQskCiVLjYddaY9ZwI8KEq6rOm5QZqgEd9Sue8nVT6yJV3MrjnxRLC4GJlZ7RKC1rDT30qxKJsVAp68A6xVwq+ntbrbE389bOHeIuIgW8mJApgqfge3IHHi2zvXXYs3xX7Qq4KIeFHv+Ea6CWSYslkgkMb3dN8NDe+PBeKZIhqfFs1TuDqXeCGSQjl1bfJESnRjA4aoLtTSVRonXlA4RCvvVxDeOx3plI+XGK3iY4oJyFQnQKTcRlTOBGZZabvqADdYS0D32Deo7OOWodoJyCdzfPfM0ocbk6+09vpERoogavhh9YrxjLOA2/h7WBp6oncgU3AheAyB+ZIR7uXOcRUt8YoV+DQ7JcD+qFgSbcoPmnsND9hcG6Pnn7XPOcrxsVTso0tznO2FikKSMkBRx0hnUOcp2ODodwYFNaRA3VNOpWlkosWgfqEO4WgwDETTwYmbQX+FIAwiYX14I+fs2roFNLU0GPrK2OqKfzJVMW7WQceTE2xgA0EoT0711SNKcMe3awehHBt+OY2ntjNvuYkyGb0tRURik8up8tiRchkeF0oKrfQi0X5qxuIXnRf7pwgPCgI8K22PqdAZKI2CQK5c9Tp3A1OFtgrT+MkfjRCL/FnaH16aD7r+ON7nzfya03qaF+w7VA/8nS2g6vAqK9Lq3spcPqF8iMxw=
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*"
